apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx
  labels:
    app: nginx
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: rvsavels.azurecr.io/appnginx
        ports:
        - containerPort: 80
        volumeMounts:
          - name: azure-fs-volume
            mountPath: /usr/share/nginx/html
      volumes:
        - name: azure-fs-volume
          persistentVolumeClaim:
            claimName: azurefs-pvc
