apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefs-pv
  namespace: nginx
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: azurefs-vid
    volumeAttributes:
      resourceGroup: example-resources
      shareName: sharename
    nodeStageSecretRef:
      name: azure-sc-secret
      namespace: nginx
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock
    - nobrl