apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefs-pvc
  namespace: nginx
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: azurefs-pv
  resources:
    requests:
      storage: 5Gi