name: Build and Deploy to ACR

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        run: |
          az login --service-principal --username ${{ secrets.AZURE_CREDENTIALS_CLIENT_ID }} --password ${{ secrets.AZURE_CREDENTIALS_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_CREDENTIALS_TENANT_ID }}

      - name: Login to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build Docker image
        working-directory: docker-images  # Specify the directory where the Dockerfile is located
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/appnginx:latest .

      - name: Push Docker image to ACR
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/appnginx:latest
